name: Deploy Graph

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install Libs
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - name: Deploy to Subgraph
        run: |
          yarn global add @graphprotocol/graph-cli
          echo "$(yarn global bin)" >> $GITHUB_PATH
          graph deploy --product hosted-service aavegotchi/xp-airdrops
        shell: bash
